Repository reach-sh/reach-lang, pull requests merged in 2021-11, with the labels that each got.

#340 CORE-684: `docker pull reachsh/reach-cli:latest` before `reach upgrade`
  reach
Labels: bug

#343 CORE-743: improve installation docs' `reach config` order
  docs-src/tut.scrbl
Labels: documentation

#345 make suggestions property denote a string array
  vsce/server/src/server.ts
Labels: IDE

#349 Change BigNumberify function to support RN
  js/stdlib/ts/CBR.ts
Labels: bug, enhancement

#347 CORE-753 add `reinstall` command for easier dev
  vsce/package.json
Labels: enhancement, IDE

#354 CORE-768: `reach config` should be less subtle about default net = 0
  hs/app/reach/Main.hs
Labels: bug, enhancement

#352 CORE 759 add compiler err JSON type for safer dev
  vsce/server/src/server.ts
Labels: IDE

#358 CORE-660 extract hard-coded keyword documentation
  vsce/compiler_outputted_files/README.md
  vsce/compiler_outputted_files/keywordToDocumentation.json
  vsce/server/src/server.ts
Labels: IDE

#365 Fix View Definition docs "during in" typo
  docs/scrbl/ref-programs-appinit.scrbl
Labels: documentation

#363 CORE-662 extract hard-coded data for compiler
  vsce/data/arrayMethods.json
  vsce/data/keywordToItemKind.json
  vsce/server/src/keywordCompletion.ts
Labels: IDE

#368 CORE-792 add documentation for `Bool`
  vsce/data/keywordToDocumentation.json
Labels: IDE

#372 Fix 5.7.1.4 Contract Handles docs typo: `input.mjs` -> `index.main.mjs`
  docs/scrbl/ref-frontends-js.scrbl
Labels: bug, documentation

#373 Fix misc typos in 5.7.1.4 Contract Handles docs
  docs/scrbl/ref-frontends-js.scrbl
Labels: documentation

#374 CORE-769 extract hard-coded command information
  vsce/Makefile
  vsce/base.package.json
  vsce/build.package.json.js
  vsce/client/src/CommandsTreeDataProvider.ts
  vsce/client/src/extension.ts
  vsce/data/commands.json
  vsce/original.package.json
  vsce/package.json
Labels: IDE

#377 CORE-758 wait for comp to finish before comp again
  vsce/server/src/server.ts
Labels: IDE

#379 make diffs more identical when using build script
  vsce/build.package.json.js
Labels: IDE

#380 push changes made by `vsce publish` command
  vsce/package-lock.json
  vsce/package.json
Labels: IDE

#381 add types to `client/src/buttons.ts` for safer dev
  vsce/client/src/buttons.ts
Labels: IDE

#385 overwrite `base.package.json` first when building
  vsce/Makefile
  vsce/build.package.json.js
Labels: IDE

#394 add missing "the" to 2.6 docs.reach.sh/tut-6.html
  docs/scrbl/tut.scrbl
Labels: documentation

#393 fix line number in 2.6 Timeouts and Participation
  docs/scrbl/tut.scrbl
Labels: documentation

#392 Doc typos: fix "behavior identically" margin notes
  docs/scrbl/ref-model.scrbl
  docs/scrbl/ref-programs-consensus.scrbl
  docs/scrbl/ref-programs-step.scrbl
Labels: documentation

#395 Fix misc typos in + reword bits of `guide-nntoks.scrbl`
  docs/scrbl/guide-nntoks.scrbl
Labels: documentation

#398 `reach hashes` should use `REACH_VERSION` rather than `:latest`
  hs/app/reach/Main.hs
Labels: bug

#397 API definition docs: fix "are may" typo and reword `ctc.apis` blurb
  docs/scrbl/ref-programs-appinit.scrbl
Labels: documentation

#404 add back hover documentation for `Reach.App`
  vsce/data/keywordToDocumentation.json
Labels: IDE

#407 add types to TypeScript file for safer development
  vsce/client/src/CommandsTreeDataProvider.ts
Labels: IDE

#409 make diagnostic `code` use err code added in #335
  vsce/server/src/server.ts
Labels: enhancement, IDE

#413 update more dependencies after adding link to err
  vsce/client/package-lock.json
  vsce/client/package.json
  vsce/client/src/extension.ts
Labels: dependencies, IDE

#415 CORE-761 make compilation use `--stop-after-eval`
  vsce/server/src/server.ts
Labels: enhancement, IDE

#416 make source of compiler diagnostics more precise
  vsce/server/src/server.ts
Labels: enhancement, IDE
