Repository reach-sh/reach-lang, pull requests merged in 2021-12, with the labels that each got.

#441 CORE-887 add new info to suggestions dropdown list
  vsce/server/src/mapKeywordsWithAPeriodToAKeywordList.ts
  vsce/server/src/server.ts
Labels: enhancement, IDE

#443 Fix rps-7-rpc/client-js concurrency for Bob participant
  examples/rps-7-rpc/client-js/index.mjs
Labels: bug

#451 update `server/package.json` vers after CORE-867
  vsce/server/package.json
Labels: IDE

#452 CORE-863: fix `rpc-view-fun` when running with CFX
  js/stdlib/ts/rpc_server.ts
Labels: bug

#454 CORE-904 add `QuickFix` "auto-correct" for header
  vsce/server/src/server.ts
Labels: enhancement, IDE

#460 CORE-920 fix extension by modifying excluded files
  vsce/.vscodeignore
Labels: IDE

#463 CORE-921 grab header from compiler err msg instead
  vsce/server/src/server.ts
Labels: enhancement, IDE
