Repository reach-sh/reach-lang, pull requests merged in 2022-05, with the labels that each got.

#888 change two instances of `{rsh}` to `{!rsh}`
  docs/src/rsh/compute/index.md
Labels: documentation

#896 improve documentation tooltips
  docs/dev/generator.js
  docs/src/assets/styles.css
Labels: documentation

#912 fix syntax error in documentation for `API`
  docs/src/rsh/appinit/index.md
Labels: documentation

#921 delete unnecessary `await`s before non-`async` fns
  vsce/server/src/server.ts
Labels: code cleanup

#872 CORE-1364: document user-tracking
  docs/src/tool/index.md
  docs/xrefs.json
Labels: documentation

#960 fix typos in `docs/src/networks/index.md`
  docs/src/networks/index.md
Labels: documentation

#975 CORE-1813 fix typo in `docs/src/model/index.md`
  docs/src/model/index.md
Labels: documentation

#762 `reach support` command
  hs/app/reach/Main.hs
Labels: enhancement, CLI

#979 delete old doc map that's now no longer necessary
  vsce/data/keywordToDocumentation.json
Labels: documentation, IDE, code cleanup

#1000 DCT-431 fix typo in `src/guide/ganache/index.md`
  docs/src/guide/ganache/index.md
Labels: documentation

#1010 DCT-432 delete trailing whitespace in `docs/src/`
  docs/src/assets/styles.css
  docs/src/cout/index.md
  docs/src/frontend/index.md
  docs/src/guide/loop-invs/index.md
  docs/src/guide/staking/index.md
  docs/src/index.md
  docs/src/quickstart/index.md
  docs/src/rsh/appinit/index.md
  docs/src/rsh/compute/index.md
  docs/src/rsh/local/index.md
  docs/src/rsh/module/index.md
  docs/src/tut/overview/index.md
  docs/src/tut/rps/index.md
Labels: code cleanup

#1055 add missing indefinite article in `index.md`
  docs/src/rsh/errors/index.md
Labels: documentation
