Repository reach-sh/reach-lang, pull requests merged in 2022-02, with the labels that each got.

#550 add missing types to parameters in `extension.ts`
  vsce/client/src/extension.ts
Labels: IDE

#545 increase visibility of `ask.ts`'s `export`s' types
  js/stdlib/ts/index.ts
  js/stdlib/webpack.config.js
Labels: enhancement, stdlib

#553 `import` url instead of `require`-ing it for types
  vsce/client/src/extension.ts
Labels: IDE

#586 increase specificity of `connector`'s type
  js/stdlib/ts/interfaces.ts
Labels: stdlib

#590 link ReactJS docs for easier access for developers
  docs/src/tut/rps/index.md
Labels: documentation

#626 docs: slightly more explanation for require and assume
  docs/src/rsh/consensus/index.md
  docs/src/rsh/local/index.md
Labels: documentation

#634 CORE-1183: fix `sed` portability issue for older Macs
  hs/app/reach/Main.hs
Labels: bug
