Repository reach-sh/reach-lang, pull requests merged in 2022-04, with the labels that each got.

#751 prevent Reach shell script downloads to every dir
  vsce/client/src/extension.ts
  vsce/package.json
  vsce/server/src/server.ts
Labels: IDE

#803 CORE-1443: make cli-tricky-directories bootstrap itself
  examples/cli-tricky-directories/  foo _ bar @ baaz /  quux/ yo-/NAME
  examples/cli-tricky-directories/ that directory with "double quotes"/NAME
  examples/cli-tricky-directories/A directory name with spaces /NAME
  examples/cli-tricky-directories/DS
  examples/cli-tricky-directories/Doesn't break/NAME
  examples/cli-tricky-directories/README.md
  examples/cli-tricky-directories/What' about 'this'?/NAME
  examples/cli-tricky-directories/foo/  quux/ yo-/NAME
  examples/cli-tricky-directories/run.sh
  examples/cli-tricky-directories/«Інтернет»/лептоп/або смартфон/NAME
  examples/cli-tricky-directories/世界您好/NAME
Labels: bug

#837 improve error handling when updating via extension
  vsce/client/src/util/update.ts
  vsce/package-lock.json
Labels: IDE

#849 fix troubleshooting typo
  docs/src/trouble/index.md
Labels: documentation
